# Generated by Django 2.1.10 on 2020-10-26 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_auto_20201023_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='file',
            field=models.FileField(blank=True, upload_to='files/%Y/%m/%d'),
        ),
    ]
